[window]
padding = { x = 7, y = 7 }
decorations = 'Buttonless'
startup_mode = 'Maximized'

[font]
normal = { family = "NotoSansM NFM", style = "Regular" }
size = 11

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
foreground = '#bbc2cf'
background ='#282c34'

[colors.cursor]
cursor = '#51afef'
text   = '#282c34'

[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#a9a1e1'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[colors.bright]
black   = '#3f444a'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#da8548'
blue    = '#51afef'
magenta = '#a9a1e1'
cyan    = '#46d9ff'
white   = '#efefef'

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
]

