add_newline = false

format = "${custom.directory}${custom.fdir}${custom.fbranch} ${custom.gbranch}[\uf0e7](bold #FFEA00) "
# 26a1
# f0e7


[custom.directory]
shell = 'zsh'
command = 'pwd | sed "s|$HOME|~|"'
when = '[[ -z ${STARSHIP_F_PREFIX-} || "$PWD" != "${STARSHIP_F_PREFIX%/}"/* ]]'
format = '[$output](bold bright-blue)'

[custom.fdir]
shell = 'zsh'
command = 'pwd | sed "s|$HOME|~|" | sed "s|^$STARSHIP_F_PREFIX/.*/||"'
when = '[[ -n ${STARSHIP_F_PREFIX-} && "$PWD" == "${STARSHIP_F_PREFIX%/}"/* ]]'
format = '[$output](bold bright-blue)'

[custom.fbranch]
shell = 'zsh'
command = 'pwd | sed "s|$HOME|~|" | sed "s|^$STARSHIP_F_PREFIX/||" | sed "s|/.*$||"'
when = '[[ -n ${STARSHIP_F_PREFIX-} && "$PWD" == "${STARSHIP_F_PREFIX%/}"/* ]]'
format = ' [ $output](bold #FFAC1C)'

[custom.gbranch]
shell = 'zsh'
command = 'git branch --show-current'
when = 'git branch --show-current 2>/dev/null'
format = '[ $output](bold #FFAC1C) '
