[gaps]
inner.horizontal = 4
inner.vertical   = 4
outer.left       = 4
outer.right      = 4
outer.top        = 4
outer.bottom     = 4

[mode.main.binding]

# ---- Focus (vim keys)
ctrl-cmd-h = "focus left"
ctrl-cmd-j = "focus down"
ctrl-cmd-k = "focus up"
ctrl-cmd-l = "focus right"

ctrl-cmd-n = 'focus-back-and-forth'
ctrl-cmd-m = 'workspace-back-and-forth'

# ---- Move windows
ctrl-alt-h = "move left"
ctrl-alt-j = "move down"
ctrl-alt-k = "move up"
ctrl-alt-l = "move right"

# ---- Layout toggles
ctrl-cmd-comma = "layout accordion horizontal vertical"
ctrl-cmd-period = "layout tiles horizontal vertical"
ctrl-cmd-slash = 'layout floating tiling'


# ---- Fullscreen toggle
ctrl-cmd-f = "fullscreen"

# ---- Workspaces (1..9)
ctrl-cmd-1 = "workspace 1"
ctrl-cmd-2 = "workspace 2"
ctrl-cmd-3 = "workspace 3"
ctrl-cmd-4 = "workspace 4"
ctrl-cmd-5 = "workspace 5"
ctrl-cmd-6 = "workspace 6"
ctrl-cmd-7 = "workspace 7"
ctrl-cmd-8 = "workspace 8"
ctrl-cmd-9 = "workspace 9"
ctrl-cmd-semicolon  = "workspace prev"
ctrl-cmd-quote = "workspace next"

# ---- Move window to workspace
ctrl-alt-1 = "move-node-to-workspace 1"
ctrl-alt-2 = "move-node-to-workspace 2"
ctrl-alt-3 = "move-node-to-workspace 3"
ctrl-alt-4 = "move-node-to-workspace 4"
ctrl-alt-5 = "move-node-to-workspace 5"
ctrl-alt-6 = "move-node-to-workspace 6"
ctrl-alt-7 = "move-node-to-workspace 7"
ctrl-alt-8 = "move-node-to-workspace 8"
ctrl-alt-9 = "move-node-to-workspace 9"
ctrl-alt-semicolon = "move-node-to-workspace next"
ctrl-alt-quote = "move-node-to-workspace prev"
