background              #080808
foreground              #D0D0D0
selection_background    #1A1A1A
selection_foreground    #D0D0D0
url_color               #D0D0D0

cursor                  #FFFFFF
cursor_text_color       #080808

active_border_color     #2A2A2A
inactive_border_color   #282828
bell_border_color       #FFFFFF

tab_bar_background      #080808
active_tab_background   #1A1A1A
active_tab_foreground   #D0D0D0
inactive_tab_background #101010
inactive_tab_foreground #282828
tab_bar_margin_color    #080808

color0  #080808
color1  #D0D0D0
color2  #D0D0D0
color3  #D0D0D0
color4  #D0D0D0
color5  #D0D0D0
color6  #D0D0D0
color7  #D0D0D0

color8  #282828
color9  #FFFFFF
color10 #FFFFFF
color11 #D0D0D0
color12 #D0D0D0
color13 #D0D0D0
color14 #D0D0D0
color15 #FFFFFF
