font_family family="NotoSansM Nerd Font Mono"

cursor_trail 1

include themes/cyberdream.conf

background_opacity .7
background_blur 70

confirm_os_window_close 0

macos_show_window_title_in none
hide_window_decorations titlebar-only
window_padding_width 4 4 4 4

enabled_layouts splits

map ctrl+s+clear_all_shortcuts yes


map ctrl+s>shift+r load_config_file

map ctrl+s>h neighboring_window left
map ctrl+s>j neighboring_window down
map ctrl+s>k neighboring_window up
map ctrl+s>l neighboring_window right

map ctrl+s>v launch --location=vsplit
map ctrl+s>n launch --location=hsplit
map ctrl+s>x close_window
map ctrl+s>z layout_action toggle_fullscreen

map --allow-fallback=shifted,ascii cmd+c copy_or_noop
map --allow-fallback=shifted,ascii cmd+v paste_from_clipboard

map --new-mode resize ctrl+s>r
map --mode resize h resize_window narrower
map --mode resize l resize_window wider
map --mode resize j resize_window shorter
map --mode resize k resize_window taller
map --mode resize q pop_keyboard_mode
map --mode resize ctrl+c pop_keyboard_mode
