font_family family="NotoSansM Nerd Font Mono"

cursor_trail 1

include themes/cyberdream.conf

background_opacity .7
background_blur 20

confirm_os_window_close 0

macos_show_window_title_in none
hide_window_decorations titlebar-only
window_padding_width 4 4 4 4
